# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4687b77de2d90db08bb401bc090f4bc60295f64f59c8a594da5e74dc91a5a2ea661ec032ac2589dc0d903c765aff84a35beabe14fdac8c44d5639f5993c57d0

test:
  secret_key_base: b3b080cd1018fe7cbf6c79ea93439b3c484d55cc4a3fac060f9429955e720d01efee4a1aceac5d33e0c5062dd667ccb25ce11904ed04cf99941b3cc0d8c90ba4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
